# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rozmu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='Czat',
        ),
        migrations.DeleteModel(
            name='Czat',
        ),
    ]
